### PR TITLE
Feature molecule visualizer

### PR DESCRIPTION
**Pull request by Miniland1333**
Finally merge in this pull request for Henry J. VCell Biosimulators visualization within LibreTexts pages.

Includes prototypical "QUICK" mode that needs further testing.

### CODE REVIEW

**Comment by ymdahi** [comment]
Hey Henry, this looks good.

Quick question: I've tried passing `'quick': 'true'` in the dekiscript template, but it seems to still go to `SLOW_API_ENDPOINT`. What value does that property expect?

**Comment by Miniland1333** [comment]
The build that is live is on Henry J's pages seems to be from `master` instead of this branch, so I will need to build these changes and then test the deployment when I have time. Also, the deployment is currently pulling from `test.libretexts.org` instead of the CDN, so I will need to change that once this PR is completed.

**Comment by Miniland1333** [comment]
It seems that while the my API tool is now working, it seems that VCell gives different results than other simulators for COMBINE archives made from VCell. Compare the following examples:
1) https://bio.libretexts.org/Sandboxes/hagnew_at_libretexts.org/VCell_Jakubowski
2) https://bio.libretexts.org/Sandboxes/hagnew_at_libretexts.org/VCell_Jakubowski_Tellurium

Since QUICK requires the use of Tellurium for speed reasons, we cannot enable QUICK mode until whatever issue in VCell or the COMBINE archive has. My gut tells me that there is something how either this tool or VCell handles the COMBINE units that is different than expected.

**Comment by Miniland1333** [comment]
Once this is eventually merged and deployed, we will need to update https://bio.libretexts.org/Template:VCell/Activity with the url to the file on the CDN.

**Review by ymdahi — APPROVED** [review]

**Pull request merged**
