### PR TITLE
Finally added some comments and documentation

### PR DESCRIPTION
**Pull request by Miniland1333**
Added in JSDoc comments for the most important files, such as endpoint.js, elevate.js, and reuse.js. Also updated various README.md to reflect the current state of the repository.

### CODE REVIEW

**Comment by ymdahi** [comment]
Henry, you're the best :gift_heart:

Just as a refresher for myself, if I accept this PR, does the build process automatically get initiated, or do I have to start the build process manually in github actions?

**Comment by Miniland1333** [comment]
> Henry, you're the best 💝
> 
> Just as a refresher for myself, if I accept this PR, does the build process automatically get initiated, or do I have to start the build process manually in github actions?

Yes, Github will automatically start the deployment process once the PR is merged into the master branch. Note that you must first approve a PR, then as the second step do the merge.

Also, as part of the PR review process, feel free to ask inline questions if any of my documentation is unclear or if there are any spots that you would be interested in me adding more. I've hopefully tagged the most important and relevant pieces of code, but let me know if there any sections in particular you want me to focus on.

**Comment by ymdahi** [comment]
Thanks Henry, I'll spend a bit of time reviewing your comments tomorrow and will take it from there.

**Comment by Miniland1333** [comment]
The reason I used the JSDoc standard is that an IDE can take advantage of the information. Webstorm uses the JSDoc information to give contextual help menus and also do some soft type-checking.
image

**Comment by ethanaturner** [comment]
Good stuff, thanks @Miniland1333! Out of curiosity before I approve, how do API/Batch changes get uploaded to the server(s)? Is it automatic or do we need to manually trigger?

**Comment by Miniland1333** [comment]
> Good stuff, thanks @Miniland1333! Out of curiosity before I approve, how do API/Batch changes get uploaded to the server(s)? Is it automatic or do we need to manually trigger?

You will need to manually upload the file to the respective server. The [PM2](https://pm2.keymetrics.io/) process will then detect the file changes and automatically restart the code. Use `pm2 list` and `pm2 monit` to see more about what is running on those servers.

**Comment by ethanaturner** [comment]
Awesome, thanks again!

**Review by ethanaturner — APPROVED** [review]
Approved by @ymdahi and @ethanaturner 10/15/21.

**Pull request merged**
