### PR TITLE
mobile version is auto compressed

### PR DESCRIPTION
**Pull request by aryanrsuri**

### CODE REVIEW

**Comment by aryanrsuri** [comment]
this is a preliminary update to get the feature out

**Comment by Miniland1333** [comment]
By mobile, are you specifically targeting portrait phone size? This would mean that landscape phone and tablet sizes would function as normal which I think is what you are intending.

**Comment by aryanrsuri** [comment]
> 
> 
> By mobile, are you specifically targeting portrait phone size? This would mean that landscape phone and tablet sizes would function as normal which I think is what you are intending.

Yes that is exactly correct

**Review by Miniland1333 — APPROVED** [review]
Thanks for the clarification, and since this is targeting mobile phone portrait this looks good to go.
-Henry

**Pull request merged**
