### PR TITLE
remove non-signed in license not set modal appearing bug

### PR DESCRIPTION
**Pull request by aryanrsuri**
quick bug accept/fix

### CODE REVIEW

**Comment by Miniland1333** [comment]
I have a feeling that having this enabled for every copy without a license could get annoying. I worry that it will show up so frequently that people will ignore it. Are you/Delmar expecting this and are okay with it?

**Comment by aryanrsuri** [comment]
> 
> 
> I have a feeling that having this enabled for every copy without a license could get annoying. I worry that it will show up so frequently that people will ignore it. Are you/Delmar expecting this and are okay with it?

Yes that is his decision

**Review by Miniland1333 — APPROVED** [review]
Approved by Delmar through Groups.io

**Comment by Miniland1333** [comment]
@aryan this PR was approved a few days ago in case you were waiting on it.

**Pull request merged**
