### PR TITLE
Add authenticated endpoints for Adapt

### PR DESCRIPTION
**Pull request by ymdahi**
Issue: #159 

@ethanaturner : is it possible to test this on dev before merge?

@kreut : once this is merged, we can test:

- [ ] retrieving tags (/tags)
- [ ] retrieving user-friendly url (/info)

### CODE REVIEW

**Review by ethanaturner — CHANGES_REQUESTED** [review]
Looks good except for `endpoint[0]` (line 105): it still contains a `/`, so the request URL has a double slash and causes `404`. If we just strip out the `/` from endpoint[0], we should be perfect 👍.

**Comment by ethanaturner** [comment]
After those changes, here's some example outputs given example input `{ "path": "354874", "subdomain": "chem", "mode": "view", "dreamformat": "json" }`:

**Tags:**
```
{
  "@count": "6",
  "@href": "https://chem.libretexts.org/@api/deki/pages/354874/tags",
  "tag": [
    {
      "@value": "article:topic-category",
      "@id": "143",
      "@href": "https://chem.libretexts.org/@api/deki/site/tags/143",
      "title": "article:topic-category",
      "type": "text",
      "uri": "https://chem.libretexts.org/Special:Tags?tag=article:topic-category"
    },
    {
      "@value": "autonumheader:yes2",
      "@id": "509160",
      "@href": "https://chem.libretexts.org/@api/deki/site/tags/509160",
      "title": "autonumheader:yes2",
      "type": "text",
      "uri": "https://chem.libretexts.org/Special:Tags?tag=autonumheader:yes2"
    },
    {
      "@value": "coverpage:yes",
      "@id": "57753",
      "@href": "https://chem.libretexts.org/@api/deki/site/tags/57753",
      "title": "coverpage:yes",
      "type": "text",
      "uri": "https://chem.libretexts.org/Special:Tags?tag=coverpage:yes"
    },
    {
      "@value": "field:genchem",
      "@id": "81007",
      "@href": "https://chem.libretexts.org/@api/deki/site/tags/81007",
      "title": "field:genchem",
      "type": "text",
      "uri": "https://chem.libretexts.org/Special:Tags?tag=field:genchem"
    },
    {
      "@value": "license:ccby",
      "@id": "63066",
      "@href": "https://chem.libretexts.org/@api/deki/site/tags/63066",
      "title": "license:ccby",
      "type": "text",
      "uri": "https://chem.libretexts.org/Special:Tags?tag=license:ccby"
    },
    {
      "@value": "showtoc:no",
      "@id": "51256",
      "@href": "https://chem.libretexts.org/@api/deki/site/tags/51256",
      "title": "showtoc:no",
      "type": "text",
      "uri": "https://chem.libretexts.org/Special:Tags?tag=showtoc:no"
    }
  ]
}
```

**Info:**
```
{
  "@id": "354874",
  "@guid": "b52c94f1a8f84c7b96662c11c5779239",
  "@draft.state": "inactive",
  "@href": "https://chem.libretexts.org/@api/deki/pages/354874?redirects=0",
  "@deleted": "false",
  "@revision": "1",
  "date.created": "Mon, 01 Nov 2021 23:37:44 GMT",
  "language": "en-US",
  "namespace": "main",
  "path": {
    "@seo": "true",
    "#text": "Sandboxes/eaturner_at_ucdavis.edu/Chemistry_(Ethan's)"
  },
  "title": "Chemistry (Ethan's)",
  "uri.ui": "https://chem.libretexts.org/Sandboxes/eaturner_at_ucdavis.edu/Chemistry_(Ethan's)"
}
```

**Comment by kreut** [comment]
HI guys,

Based on what Ethan wrote above as the example output, this is exactly what I'm hoping for.  Can someone please shoot me an email when this is merged.  For some reason, I'm still not getting notifications about this thought it looks like I'm subscribed.

Thanks so much!

**Comment by ymdahi** [comment]
@ethanaturner: I've made the recommended changes (thx!). Should be good to merge. Let me know if you can get to this tomorrow, otherwise I'll jump in.

**Comment by ethanaturner** [comment]
Awesome! I'll get this onto production tomorrow/today!

**Review by ethanaturner — APPROVED** [review]
Reviewed and approved 11/5/21.

**Pull request merged**
